# 站点配置

# 引入主题
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果与 `_data/locales` 目录中的文件名相同，则页面界面语言也会随之改变，
# 否则将使用默认值 'en'。
lang: zh-CN

# 设置你的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: DoHoKun # 站点主标题

tagline: Hajimi Nameiluduo # 将显示为副标题

description: >- # 用于 SEO 元信息和 Atom feed
  DoHoKun's Blog

# 填写你站点的协议与主机名。
# 例如 'https://username.github.io'，注意末尾不要以 '/' 结尾。
url: "https://dhkun.github.io"

github:
  username: DHKun # 改为你的 GitHub 用户名

twitter:
  username: twitter_username # 改为你的 Twitter 用户名

social:
  # 改为你的姓名。
  # 将显示为文章的默认作者与页脚的版权拥有者
  name: DoHoKun
  email: 2727461997@qq.com # 改为你的邮箱地址
  links:
    # 第一个元素将作为版权拥有者的链接
    - https://twitter.com/username # 改为你的 Twitter 主页
    - https://github.com/DHKun # 改为你的 GitHub 主页
    # 取消注释以下示例以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 站点验证设置
webmaster_verifications:
  google: # 填写你的 Google 站点验证代码
  bing: # 填写你的 Bing 站点验证代码
  alexa: # 填写你的 Alexa 站点验证代码
  yandex: # 填写你的 Yandex 站点验证代码
  baidu: # 填写你的 Baidu 站点验证代码
  facebook: # 填写你的 Facebook 站点验证代码

# ↑ --------------------------
# 以上为 `jekyll-seo-tag` 设置

# 网站分析设置
analytics:
  google:
    id: # 填写你的 Google Analytics（GA）ID
  goatcounter:
    id: # 填写你的 GoatCounter ID
  umami:
    id: # 填写你的 Umami 站点 ID
    domain: # 填写你的 Umami 域名
  matomo:
    id: # 填写你的 Matomo 站点 ID
    domain: # 填写你的 Matomo 域名
  cloudflare:
    id: # 填写你的 Cloudflare Web Analytics 令牌
  fathom:
    id: # 填写你的 Fathom 站点 ID

# 页面浏览量设置
pageviews:
  provider: # 目前仅支持 'goatcounter'

# 颜色主题偏好设置。
#
# 注意：留空则默认跟随系统偏好，
# 侧边栏左下角会显示深浅主题切换开关。
#
# 可选值：
#
#     light — 使用浅色主题
#     dark — 使用深色主题
#
theme_mode: light # [light | dark]

# 媒体资源的 CDN 端点。
# 注意：一旦配置，所有以 '/' 开头的媒体资源路径（站点头像、文章图片、音视频等）
# 都会自动加上该 CDN 前缀。
#
# 示例：'https://cdn.com'
cdn:

# 侧边栏头像，支持本地或跨域（CORS）资源
avatar: https://avatars.githubusercontent.com/u/153045411?u=4d1eaab2ec2ca01bf87c54acda163b9ac1c05a9b&v=4&size=64

# 用于 SEO `og:image` 元标签的全站默认社交分享图 URL。
# 可在文章 Front Matter 中通过 `image` 覆盖。
social_preview_image: # string, local or CORS resources

# 布尔类型，文章目录（TOC）的全局开关。
toc: true

comments:
  # 评论系统全局开关；留空表示禁用。
  provider: giscus # [disqus | utterances | giscus]
  # 各评论提供方的配置如下：
  disqus:
    shortname: # 填写 Disqus 的 shortname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 设置 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus 选项 › https://giscus.app
  giscus:
    repo: DHKun/dhkun.github.io # <gh-username>/<repo>
    repo_id: R_kgDOPaTlxA
    category: Announcements
    category_id: DIC_kwDOPaTlxM4Ct7Ou
    mapping: title # 可选，默认 'pathname'
    strict: 0 # 可选，默认 '0'
    input_position: top # 可选，默认 'bottom'
    lang: zh-CN # 可选，默认使用 `site.lang`
    reactions_enabled: 1 # 可选，默认 '1'
    loading: lazy
    emit_metadata: 0

# 自托管主题静态资源（可选）› https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值，留空视为 false
    # 指定 Jekyll 环境；留空代表开发与生产环境均启用
    # 仅当 `assets.self_host.enabled` 为 true 时生效
    env: # [development | production]

pwa:
  enabled: true # PWA 可安装功能开关
  cache:
    enabled: true # 离线缓存开关
    # 这里定义的路径将被排除在 PWA 缓存之外。
    # 通常用于与当前站点同域的另一个站点，其值常设为该站点的 `baseurl`。
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URL 将不会被 PWA 缓存

paginate: 10

# 站点的基础路径（baseurl）
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 选项 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 为空字符串表示项目中所有文件
      type: posts
    values:
      layout: post
      comments: true # 启用文章评论
      toc: true # 显示文章目录栏
      # 除非你非常确认，否则不要修改下面的参数，
      # 否则需要同步更新项目中所有文章链接相关的代码。
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 见 `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
